<?php

declare(strict_types=1);

namespace AtlasCache\Config;

use AtlasCache\Storage\CachePaths;
use RuntimeException;

final class RuntimeConfigWriter
{
    private CachePaths $paths;
    private SettingsRepository $settings;

    public function __construct(CachePaths $paths, SettingsRepository $settings)
    {
        $this->paths = $paths;
        $this->settings = $settings;
    }

    public function write(): void
    {
        $settings = $this->settings->all();
        $refreshToken = $this->settings->ensureRefreshToken();
        $config = [
            'enabled' => (bool) $settings['enabled'],
            'cache_root' => $this->paths->root(),
            'ttl' => (int) $settings['ttl'],
            'stale_while_revalidate' => (bool) $settings['stale_while_revalidate'],
            'debug_headers' => (bool) $settings['debug_headers'],
            'frontend_debug_enabled' => $this->frontendDebugActive($settings),
            'frontend_debug_expires_at' => $this->frontendDebugExpiresAt($settings),
            'refresh_token' => $refreshToken,
            'allowed_hosts' => $this->allowedHosts(),
            'sensitive_cookies' => array_values((array) $settings['sensitive_cookies']),
            'excluded_url_patterns' => array_values((array) $settings['excluded_url_patterns']),
            'query_string_whitelist' => array_values((array) $settings['query_string_whitelist']),
        ];

        $contents = "<?php\n\n// Generated by Atlas Cache. Do not edit manually.\nreturn " . var_export($config, true) . ";\n";
        $this->atomicWrite($this->paths->configFile(), $contents);
    }

    /**
     * Hostnames the drop-in is allowed to build/serve cache entries for. Requests with an
     * unrecognised Host header are bypassed instead of creating new cache directories, so a
     * spoofed Host cannot be used to grow the cache store without bound.
     *
     * @return list<string>
     */
    private function allowedHosts(): array
    {
        $hosts = [
            $this->hostFromUrl(home_url('/')),
            $this->hostFromUrl(site_url('/')),
        ];

        if (is_multisite() && function_exists('get_sites')) {
            foreach (get_sites(['number' => 200, 'fields' => 'ids']) as $siteId) {
                $hosts[] = $this->hostFromUrl(get_home_url((int) $siteId, '/'));
            }
        }

        return array_values(array_unique(array_filter($hosts, static fn (string $host): bool => $host !== '')));
    }

    private function hostFromUrl(string $url): string
    {
        $host = wp_parse_url($url, PHP_URL_HOST);

        return is_string($host) ? strtolower($host) : '';
    }

    /**
     * @param array<string, mixed> $settings
     */
    private function frontendDebugActive(array $settings): bool
    {
        if (empty($settings['frontend_debug_enabled'])) {
            return false;
        }

        $expiresAt = $this->frontendDebugExpiresAt($settings);

        return $expiresAt > time();
    }

    /**
     * @param array<string, mixed> $settings
     */
    private function frontendDebugExpiresAt(array $settings): int
    {
        $enabledAt = (int) ($settings['frontend_debug_enabled_at'] ?? 0);
        if ($enabledAt <= 0) {
            return 0;
        }

        return $enabledAt + ((int) $settings['frontend_debug_expires_after_days'] * DAY_IN_SECONDS);
    }

    private function atomicWrite(string $target, string $contents): void
    {
        $directory = dirname($target);
        if (!is_dir($directory) && !wp_mkdir_p($directory)) {
            throw new RuntimeException('Nelze vytvořit adresář pro runtime config.');
        }

        $temporary = $target . '.tmp.' . bin2hex(random_bytes(6));
        if (file_put_contents($temporary, $contents, LOCK_EX) === false) {
            throw new RuntimeException('Nelze zapsat runtime config.');
        }

        if (!@rename($temporary, $target)) {
            @unlink($temporary);
            throw new RuntimeException('Nelze atomicky nahradit runtime config.');
        }
    }
}
